### PR TITLE
Fix deploy workflow

### LINKED ISSUE #21: Deployment workflow broken
https://github.com/napari/napari-console/actions/runs/2999115117

needs update to setup.cfg/pyproject.toml build

cc @Carreau

### PR DESCRIPTION
**Pull request by Czaki**
@alisterburt, here bugfix for too fast merge.

closes #21

### CODE REVIEW

**Comment by alisterburt** [comment]
Apologies, was about to jump on a plane! 😅 thanks!

**Comment by alisterburt** [comment]
Can you push a tag to check deployment if you have write access?

**Comment by Czaki** [comment]
pushed

**Comment by Carreau** [comment]
AH, thanks.

**Pull request merged**
