### PR TITLE
Migrate to npe2

### PR DESCRIPTION
**Pull request by Czaki**
This migrate napari-console to npe2. It silences 
```
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```
warning on napari startup 

closes napari/napari#6286

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
Finally, these warnings are so annoying!

**Review by DragaDoncila — APPROVED** [review]
Looks good to me! Pulled down and it works so, ship it 🎉

**Comment by nclack** [comment]
Do you still need the `napari-plugin-engine` dependency?

**Comment by Czaki** [comment]
good spot. Removed

**Review by psobolewskiPhD — APPROVED** [review]
❤️

**Comment by DragaDoncila** [comment]
@Czaki I think we should release, yes?

**Pull request merged**
